<?php

return [
    'identity' => [
        'name'   => 'Daniel Andrei Salipot',
        'handle' => 'daniel.salipot',
        'role'   => 'Software engineer building production web systems with hardware integration.',
        'tagline' => 'Software engineer. End-to-end builds.',
        'location' => ['city' => 'Marilao, PH', 'tz' => 'UTC+8'],
        'available' => [
            'status' => 'open',
            'since'  => 'Q3 2026',
            'label'  => 'available for hire · q3 2026',
        ],
    ],
    'links' => [
        'email'    => 'danielsalipot@gmail.com',
        'phone'    => '+63 939 504 4799',
        'github'   => 'https://github.com/danielsalipot',
        'linkedin' => 'https://linkedin.com/in/daniel-salipot',
    ],
    'stats' => [
        ['n' => '3',   'l' => 'years shipping'],
        ['n' => '12+', 'l' => 'production systems'],
        ['n' => '1st', 'l' => 'hack4impact 2025'],
    ],
    'now' => [
        ['label' => 'building',     'title' => 'Personal portfolio v1',      'sub' => 'laravel · inertia · react · the site you\'re looking at'],
        ['label' => 'last shipped', 'title' => 'OASYS HRIS',                 'sub' => 'capstone · best of department, adamson 2023'],
        ['label' => 'learning',     'title' => 'Go + Inertia.js',            'sub' => 'exploring a laravel-to-go migration for fun'],
    ],
    'projects' => [
        [
            'slug' => 'oasys', 'name' => 'OASYS', 'kicker' => 'Overall Administering System',
            'year' => '2023', 'featured' => true, 'tag' => 'Capstone · Best of department',
            'blurb' => "End-to-end Human Resource Information System with integrated Philippine-compliant payroll engine. Five user roles, twenty-plus modules, automated SSS / PhilHealth / Pag-IBIG / Withholding computation, and signed PDF payroll generation - built solo as the lead software engineer.",
            'stack' => ['laravel', 'php', 'mysql', 'bootstrap'],
            'lang' => 'php', 'branch' => 'main', 'hash' => 'a4f9c1d',
            'screenshot' => ['title' => 'oasys.adamson.local', 'subtitle' => 'hris · payroll · dtr · roles', 'tone' => 'forest'],
            'metrics' => [['20+', 'modules'], ['5', 'user roles'], ['Best', 'capstone 2023']],
            'case_study' => [
                'problem' => "HR departments in Philippine institutions juggle a brutal stack of paperwork - DTR tracking, leave applications, deduction tables, government contribution schedules (SSS, PhilHealth, Pag-IBIG, Withholding Tax), 15-day payroll cutoffs, and onboarding/offboarding paperwork - usually across spreadsheets, paper, and disconnected systems. There was no single source of truth: a payroll cycle could take days, leave requests got lost between approvers, and recomputing a deduction meant manual maths every cutoff.",
                'role'    => "Solo developer and lead software engineer / designer. Owned the entire system end-to-end: requirements gathering, database schema, role-based access control for five user types, all twenty-plus modules, the payroll computation engine (with Philippine government contribution tables), PDF generation with e-signature support, and deployment. Team of four total - the other members handled documentation, presentation, and research; the codebase and architecture were mine.",
                'outcome' => "Awarded Best Capstone of the IT&IS Department, Adamson University, 2023. The system runs the full HR lifecycle: applicant intake → onboarding → daily DTR and attendance → leave / overtime / cash advance workflows with approval chains → automated 15-day payroll computation → signed payroll PDF generation → offboarding. Tested with realistic employee data covering multiple positions, departments, and pay rates.",
                'links'   => ['live' => null, 'repo' => 'https://github.com/danielsalipot/OASYS'],
                'modules' => [
                    ['name' => 'Payroll Engine',       'desc' => '15-day cutoff cycles with automated computation of Gross, SSS, PhilHealth, Pag-IBIG, Withholding Tax, and Net Pay'],
                    ['name' => 'Salary Management',    'desc' => 'Per-position averages, top-earner rankings, and rate-per-hour editing with audit trail'],
                    ['name' => 'Deductions',           'desc' => 'Multi-employee bulk deduction creation, period-split across days, with approval and removal flows'],
                    ['name' => 'Overtime',             'desc' => 'Auto-detected from DTR excess hours, with approval / denial workflow and paid-overtime tracking'],
                    ['name' => 'Cash Advance',         'desc' => 'Request, approval, and amortization across pay periods, with running balance per employee'],
                    ['name' => 'Contributions',        'desc' => 'Government-compliant SSS, PhilHealth, Pag-IBIG, and Withholding Tax with bracket lookups per pay period'],
                    ['name' => 'Bonus & Multi-Pay',    'desc' => 'Ad-hoc bonus disbursement and multi-period payroll consolidation'],
                    ['name' => 'Leave',                'desc' => 'Application, approval workflow with manager routing, and balance accrual per employee'],
                    ['name' => 'Attendance & DTR',     'desc' => 'Daily time record with schedule comparison, late-tracking, and excess-hour detection'],
                    ['name' => 'Onboarding / Offboarding', 'desc' => 'Applicant pipeline from interview through hire to exit checklist, with status tracking'],
                    ['name' => 'Performance Assessment','desc' => 'Periodic evaluations with module-based scoring and HR Admin review'],
                    ['name' => 'Audit Logs',           'desc' => 'Cross-module activity log capturing who changed what, when, and from where'],
                ],
                'screenshots' => [
                    [
                        'src'     => '/projects/oasys/01-salary-management.jpg',
                        'caption' => 'Salary Management - per-position salary averages with top-3 earners per role and inline rate editing',
                        'alt'     => 'OASYS Salary Management page showing average salary per position cards with top earners listed',
                    ],
                    [
                        'src'     => '/projects/oasys/02-payroll-details.jpg',
                        'caption' => 'Payroll Details Table - per-employee row with auto-computed Total Hours, Rate/hr, Bonus, Gross Pay, SSS, Pag-IBIG, PhilHealth, Deductions, Taxable Net, Withholding Tax, and Total Salary',
                        'alt'     => 'Payroll details table with employee rows and computed columns including government contributions',
                    ],
                    [
                        'src'     => '/projects/oasys/03-payroll-report.jpg',
                        'caption' => 'Payroll Report Generation - 15-day cutoff picker with Create Payroll (e-signature upload + PDF output) and View Payroll History',
                        'alt'     => 'Payroll report generation panel showing current cutoff dates and create payroll button',
                    ],
                    [
                        'src'     => '/projects/oasys/04-overtime-approval.jpg',
                        'caption' => 'Overtime Approval Dialog - auto-detected excess-hour record awaiting Payroll Manager approval, with employee, schedule, and computed hours',
                        'alt'     => 'Continue to Pay Overtime modal showing employee details and computed excess hours',
                    ],
                    [
                        'src'     => '/projects/oasys/05-bonus-dialog.jpg',
                        'caption' => 'Bonus Disbursement Dialog - ad-hoc bonus entry that flows directly into the next payroll cutoff',
                        'alt'     => 'Bonus Details modal with date and amount fields',
                    ],
                ],
            ],
        ],
        [
            'slug' => 'ralli', 'name' => 'Ralli', 'kicker' => 'Badminton queue and rating platform',
            'year' => '2026', 'featured' => false, 'tag' => 'In progress',
            'blurb' => 'Session queue management for badminton courts: longest-wait-first bench ordering, live matchup generation, and an ELO rating engine. Laravel API with WebSocket broadcasting, paired with a React Native client.',
            'stack' => ['laravel', 'php', 'react', 'mysql'],
            'lang' => 'php', 'branch' => 'main', 'hash' => '1b45c35',
            'screenshot' => ['title' => 'ralli/queue', 'subtitle' => 'bench · matchups · elo', 'tone' => 'ocean'],
            'metrics' => [['24', 'tables'], ['67', 'client screens'], ['ELO', 'rating engine']],
            'case_study' => [
                'problem' => 'Open-play badminton sessions run on paper lists and shouted names. Players lose track of queue position, hosts rebuild matchups by hand between every game, and there is no record of who played whom or how balanced the matches were.',
                'role' => 'Solo developer. API design, 24-table schema, queue ordering, matchup generation, ELO and co-play history tracking, real-time broadcasting, and the React Native client.',
                'outcome' => 'Active build. Schema is frozen at v1 and documented. Core loop runs end to end: RSVP, bench queue with longest-wait-first ordering, matchup generation, set scoring, and ELO updates with history. Not yet released.',
                'links' => ['live' => null, 'repo' => 'https://github.com/danielsalipot/ralli'],
                'modules' => [
                    ['name' => 'Bench Queue', 'desc' => 'Longest-wait-first ordering with indexed hot-path queries on session, status, and join time'],
                    ['name' => 'Matchup Engine', 'desc' => 'Generates balanced pairings from the active bench, tracks per-set scoring'],
                    ['name' => 'ELO Ratings', 'desc' => 'Per-sport rating with full history for sparkline rendering and co-play weighting'],
                    ['name' => 'Trust & Reviews', 'desc' => 'Polymorphic reviews across hosts and players, aggregated into trust scores'],
                    ['name' => 'Realtime', 'desc' => 'Laravel Reverb WebSocket broadcasting so queue changes land on every client instantly'],
                    ['name' => 'Auth & Identity', 'desc' => 'Sanctum tokens for the mobile client, Socialite OAuth, push token registry'],
                ],
            ],
        ],
        [
            'slug' => 'terra', 'name' => 'Terra', 'kicker' => 'Hiking trip booking platform',
            'year' => '2026', 'featured' => false, 'tag' => 'In progress',
            'blurb' => 'Marketplace connecting hike organisers with joiners: trip listings with departures and price tiers, reservations, QR-coded meetups, payment submission review, and waitlists.',
            'stack' => ['laravel', 'php', 'livewire', 'mysql'],
            'lang' => 'php', 'branch' => 'main', 'hash' => 'c4e2b19',
            'screenshot' => ['title' => 'terra/trips', 'subtitle' => 'trips · reservations · hosts', 'tone' => 'forest'],
            'metrics' => [['23', 'models'], ['QR', 'meetup check-in'], ['Livewire', 'volt']],
            'case_study' => [
                'problem' => 'Local hiking groups organise trips through group chats and spreadsheets. Slots get double-booked, payment proofs get buried in message threads, and there is no reliable headcount at the meetup point on departure day.',
                'role' => 'Solo developer. Domain modelling across 23 models, host and joiner flows, reservation and waitlist logic, payment submission review, and QR-based meetup check-in.',
                'outcome' => 'Active build. Host trip creation, departures with price tiers, joiner reservations, waitlists, and QR meetup check-in are working. Not yet released.',
                'links' => ['live' => null, 'repo' => 'https://github.com/danielsalipot/terra'],
                'modules' => [
                    ['name' => 'Trips & Departures', 'desc' => 'Trip drafts through published listings with destinations, inclusions, hike details, and tiered pricing'],
                    ['name' => 'Reservations', 'desc' => 'Slot booking with participant records and automatic waitlist promotion'],
                    ['name' => 'Meetups', 'desc' => 'QR-coded meetup points with host presets for repeat departure locations'],
                    ['name' => 'Payments', 'desc' => 'Payment submission with proof upload and host-side review queue'],
                    ['name' => 'Host Profiles', 'desc' => 'Public host pages with posts, photos, and review aggregation'],
                    ['name' => 'Auth', 'desc' => 'Socialite OAuth plus magic-link sign-in for low-friction joiner onboarding'],
                ],
            ],
        ],
        [
            'slug' => 'date-tracker', 'name' => 'Date Tracker', 'kicker' => 'Local-first couples date journal',
            'year' => '2026', 'featured' => false, 'tag' => 'In progress',
            'blurb' => 'Expo app that models each date as a timeline of stops rather than one event. Fully local-first on SQLite, with on-device receipt OCR to capture what each stop cost.',
            'stack' => ['react', 'typescript', 'sql'],
            'lang' => 'typescript', 'branch' => 'main', 'hash' => '2ad9579',
            'screenshot' => ['title' => 'date-tracker', 'subtitle' => 'stops · memories · spend', 'tone' => 'plum'],
            'metrics' => [['28', 'screens'], ['Local', 'first'], ['OCR', 'receipt capture']],
            'case_study' => [
                'problem' => 'Shared-expense apps treat a night out as a single line item, which loses the shape of the evening. A date is usually several stops, and the memory of it lives in the sequence, not the total.',
                'role' => 'Solo developer. Data model, local-first persistence with Drizzle over SQLite, OCR capture pipeline, and the full UI including Skia-rendered views.',
                'outcome' => 'Active build. Date composition with multiple stops, per-date ratings, favourites, and the memories timeline are working. Not yet released.',
                'links' => ['live' => null, 'repo' => 'https://github.com/danielsalipot/date-tracker'],
                'modules' => [
                    ['name' => 'Stop Timeline', 'desc' => 'A date is composed of ordered stops, each with its own place, spend, and notes'],
                    ['name' => 'Receipt OCR', 'desc' => 'On-device ML Kit text recognition pulls totals from photographed receipts'],
                    ['name' => 'Memories', 'desc' => 'Chronological view of past dates with ratings and favourites'],
                    ['name' => 'Local-first Storage', 'desc' => 'Drizzle ORM over on-device SQLite, no account and no network dependency'],
                ],
            ],
        ],
        [
            'slug' => 'dumagat-remontado', 'name' => 'Dumagat Remontado', 'kicker' => 'University outreach informational site',
            'year' => '2022', 'featured' => false, 'tag' => 'University outreach',
            'blurb' => 'Cultural informational site for the Dumagat Remontado tribe (Adamson outreach).',
            'stack' => ['laravel', 'bootstrap'],
            'lang' => 'php', 'branch' => 'archive', 'hash' => 'e3b7c44',
            'screenshot' => ['title' => 'dumagat-tribe.ph', 'subtitle' => null, 'tone' => 'forest'],
            'metrics' => [['Outreach', 'project'], ['Adamson', 'university'], ['2022', 'shipped']],
            'case_study' => [
                'problem' => 'The Dumagat Remontado tribe lacked digital presence and accessible information about their culture.',
                'role' => 'Team developer - Laravel + Bootstrap implementation.',
                'outcome' => 'Public informational site supporting visibility of the tribe and its traditions.',
                'links' => ['live' => null, 'repo' => null],
            ],
        ],
        [
            'slug' => 'akai-tsuki', 'name' => 'Akai Tsuki', 'kicker' => 'Jewelry shop POS · desktop',
            'year' => '2019', 'featured' => false, 'tag' => 'Coursework',
            'blurb' => 'Windows desktop point-of-sale for a jewelry shop. Role-based login, tabbed product catalog across five categories, cart with VAT computation and change calculation, receipt printing, and user account management.',
            'stack' => ['c#', 'sql'],
            'lang' => 'c#', 'branch' => 'archive', 'hash' => 'a4a1t5k',
            'screenshot' => ['title' => 'AkaiTsuki.exe', 'subtitle' => 'pos · accounts · receipts', 'tone' => 'ember'],
            'metrics' => [['5', 'catalog tabs'], ['3', 'user roles'], ['2019', 'coursework']],
            'case_study' => [
                'problem' => 'Coursework brief: build a desktop point-of-sale. A jewelry counter made the requirements concrete. Items are individually identified rather than barcoded in bulk, staff need to see the piece before selling it, and every sale has to produce a correct receipt with Philippine VAT and cash change.',
                'role' => 'Solo build in C# WinForms against SQL Server. Designed the schema, the MDI shell and form navigation, the transaction and computation logic, receipt output, and role-based access across clerk, supervisor, and customer accounts.',
                'outcome' => 'Delivered as coursework in 2019. My first database-backed application and the first time I owned a full CRUD and transaction flow end to end. Source is lost, only screenshots survive.',
                'links' => ['live' => null, 'repo' => null],
                'modules' => [
                    ['name' => 'Point of Sale', 'desc' => 'Item lookup by ID, quantity stepper, running cart, 12% VAT and net total, amount given with change computation'],
                    ['name' => 'Product Catalog', 'desc' => 'Tabbed browsing across rings, necklaces, earrings, bracelets, and watches with per-item photo, ID, and material description'],
                    ['name' => 'User Accounts', 'desc' => 'Full CRUD over staff and customer records with username search, typed roles, and assigned positions'],
                    ['name' => 'Authentication', 'desc' => 'Login gate with password visibility toggle, routing each role to its permitted forms'],
                    ['name' => 'Receipts', 'desc' => 'Transaction ID and date stamped per sale, cashier attribution, printed receipt output'],
                    ['name' => 'Shell', 'desc' => 'MDI parent with sidebar navigation and a status bar reporting the active form'],
                ],
            ],
        ],
        [
            'slug' => 'wonder', 'name' => 'Wonder', 'kicker' => 'Art marketplace · school project',
            'year' => '2021', 'featured' => false, 'tag' => 'Coursework',
            'blurb' => 'Storefront for art materials, paintings, and sculptures. Category browsing, cart, order placement, and per-artwork comments, built in plain PHP and MySQL with no framework.',
            'stack' => ['php', 'mysql', 'html', 'css'],
            'lang' => 'php', 'branch' => 'archive', 'hash' => 'w0nd3r1',
            'screenshot' => ['title' => 'wonder/home', 'subtitle' => 'catalog · cart · comments', 'tone' => 'paper'],
            'metrics' => [['6', 'categories'], ['2021', 'coursework'], ['No', 'framework']],
            'case_study' => [
                'problem' => 'Coursework brief: build a working ecommerce site end to end. I picked an art marketplace so the catalog had to hold two different product shapes at once, consumable art materials with stock and price, and one-off artworks that also needed provenance text and a discussion thread.',
                'role' => 'Solo build. Schema, catalog and category routing, cart and order flow, comment threads, and the front-end. No framework, so sessions, queries, and templating were all hand-rolled.',
                'outcome' => 'Delivered as coursework in 2021. Source is lost, only screenshots survive. Kept here as an honest marker of where I started: the same catalog, cart, and moderation concerns I now solve with Laravel, written by hand at the time.',
                'links' => ['live' => null, 'repo' => null],
                'screenshots' => [
                    [
                        'src' => '/projects/wonder/01-landing.jpg',
                        'caption' => 'Landing page. Dictionary-entry hero setting the brand, with category nav across paintings, sculptures, and art materials.',
                        'alt' => 'Wonder landing page with a dictionary-style definition of the word wonder and a top navigation bar',
                    ],
                    [
                        'src' => '/projects/wonder/02-catalog.jpg',
                        'caption' => 'Art materials catalog. Sidebar category filter across six product groups, product grid with peso pricing and add-to-cart.',
                        'alt' => 'Colored pencils category page showing a sidebar of categories and a grid of product cards with prices',
                    ],
                    [
                        'src' => '/projects/wonder/03-artwork-detail.jpg',
                        'caption' => 'Artwork listing. Provenance copy alongside order placement and a per-artwork comment thread.',
                        'alt' => 'Artwork listing for the Venus of Willendorf with description, place order button, and a comment form',
                    ],
                ],
            ],
        ],
        [
            'slug' => 'skills-olympics', 'name' => 'Skills Olympics', 'kicker' => '1st runner-up · web design',
            'year' => '2022', 'featured' => false, 'tag' => '1st runner-up',
            'blurb' => 'Competition entry - represented Adamson at the I.T. Skills Olympics 2022, U-Makati.',
            'stack' => ['html', 'css', 'figma'],
            'lang' => 'html', 'branch' => 'competition', 'hash' => 'f48d910',
            'screenshot' => ['title' => 'olympics.entry', 'subtitle' => null, 'tone' => 'slate'],
            'metrics' => [['1st', 'runner-up'], ['~30', 'schools'], ['U-Makati', 'venue']],
            'case_study' => [
                'problem' => 'Competition brief: design a web page in a fixed time window evaluated by a panel.',
                'role' => 'Sole designer + developer - represented Adamson University.',
                'outcome' => '1st runner-up against ~30 schools.',
                'links' => ['live' => null, 'repo' => null],
            ],
        ],
    ],
    'stack' => [
        'backend'   => [['Laravel', 'expert · 6y'], ['Livewire', 'expert · 3y'], ['Filament', 'advanced · 2y'], ['PHP', 'expert · 6y'], ['MySQL', 'advanced · 6y']],
        'frontend'  => [['React', 'advanced · 3y'], ['Vue.js', 'advanced · 3y'], ['Tailwind', 'expert · 4y'], ['Flutter', 'mid · 2y'], ['JavaScript', 'advanced · 5y']],
        'platforms' => [['Linux', 'comfortable'], ['Git', 'daily'], ['n8n', 'comfortable'], ['CI/CD', 'comfortable'], ['Android (Kotlin)', 'mid']],
        'adjacent'  => [['Figma · UI/UX', 'daily'], ['IoT integration', 'RFID · biometric'], ['Webhooks · APIs', 'daily'], ['Agile · Scrum', 'team lead'], ['Client comms', 'lead']],
    ],
    'experience' => [
        [
            'from' => '01.2023', 'to' => 'current',
            'role' => 'Web Application Developer', 'org' => 'Rakso CT', 'loc' => 'Marilao, PH',
            'note' => 'End-to-end software engineering across multiple production systems - system design, performance optimization, complex business logic, hardware integration (RFID, biometric, turnstile, QR), and automation pipelines via n8n and webhooks. Stack: Laravel, Livewire, Filament, MySQL. Direct client comms and project delivery.',
            'stack' => ['laravel', 'livewire', 'filament', 'mysql', 'n8n'],
            // IoT / hardware capabilities exercised during this role.
            // Tech-first framing: lead with the technology stack, not the
            // system name. Keeps NDA-safe (no client systems referenced)
            // and reads as a capabilities showcase rather than a project list.
            'projects' => [
                [
                    'tech' => ['RFID readers', 'Turnstile relays', 'Balance ledger', 'SMS gateway'],
                    'context' => 'Tap-to-pay payment platforms - card scan to relay actuation in <200ms',
                ],
                [
                    'tech' => ['Biometric scanners', 'QR codes', 'Scanner SDKs'],
                    'context' => 'Daily attendance check-in with same-day SMS to parents',
                ],
                [
                    'tech' => ['Serial protocols', 'n8n workflows', 'Webhook bridges'],
                    'context' => 'Hardware-to-Laravel automation - devices, printers, and event glue',
                ],
            ],
        ],
        [
            'from' => '01.2022', 'to' => '12.2022',
            'role' => 'Web Application Developer', 'org' => 'Adamson University', 'loc' => 'Manila, PH',
            'note' => 'Member of the team that built an informational site for the Dumagat Remontado Tribe (university outreach). Laravel + Bootstrap.',
            'stack' => ['laravel', 'php', 'bootstrap'],
            'projects' => [],
        ],
    ],
    'education' => [
        [
            'yr' => '2019 - 2023', 'degree' => 'BS Information Technology', 'org' => 'Adamson University · Manila',
            'note' => 'Capstone: OASYS (HRIS + payroll). Best of Department.',
            'honor' => 'summa cum laude', 'gpa' => '1.182 / 1.000', 'active' => true,
        ],
        [
            'yr' => '2017 - 2019', 'degree' => 'Senior High · STEM, Technology Track', 'org' => 'Adamson University · Manila',
            'note' => 'Foundations in programming, math, electronics.',
            'honor' => 'with honors', 'gpa' => null, 'active' => false,
        ],
    ],
    'certifications' => [
        [
            'org' => 'Microsoft', 'org_mark' => 'MS', 'org_bg' => '#00A4EF',
            't' => 'Technology Associate', 'sub' => 'Database Management Fundamentals',
            'yr' => '2021', 'cred' => 'MTA-098-DM', 'status' => 'verified',
            'skills' => ['sql', 'mysql', 'schemas', 'normalization'],
        ],
        [
            'org' => 'PSITE', 'org_mark' => 'PS', 'org_bg' => '#7C3AED',
            't' => '3rd Philippine Skilling Summit', 'sub' => 'Agile Methodologies Track',
            'yr' => '2022', 'cred' => 'PSS-22-AGM-417', 'status' => 'verified',
            'skills' => ['scrum', 'kanban', 'sprint planning'],
        ],
        [
            'org' => 'Adamson Univ.', 'org_mark' => 'AU', 'org_bg' => '#1F4D8B',
            't' => 'IT Skills Olympics 2022', 'sub' => 'Web Design · 1st Runner-up',
            'yr' => '2022', 'cred' => 'ITSO-22-WD-002', 'status' => 'verified',
            'skills' => ['html', 'css', 'figma'],
        ],
    ],
    'achievements' => [
        ['yr' => '2025', 't' => '1st Place',      'where' => 'Hack4Impact Hackathon',  'note' => 'Led the team - built a real-time classroom platform in 24 hours.'],
        ['yr' => '2023', 't' => 'Best Capstone',  'where' => 'AdU IT&IS Department',   'note' => 'OASYS - HRIS with integrated payroll system.'],
        ['yr' => '2022', 't' => '1st Runner-up',  'where' => 'I.T. Skills Olympics',   'note' => 'Web Design · U-Makati · ~30 schools.'],
        ['yr' => '2021', 't' => 'Microsoft Cert.','where' => 'Database Management',    'note' => 'Technology Associate, fundamentals.'],
    ],
];
