<?php

return [
    'identity' => [
        'name'   => 'Daniel Andrei Salipot',
        'handle' => 'daniel.salipot',
        'role'   => 'Backend developer building production systems end to end, from database design to hardware.',
        'tagline' => 'Backend developer. End-to-end ownership.',
        'location' => ['city' => 'Marilao, Bulacan, PH', 'tz' => 'UTC+8'],
        'available' => [
            'status' => 'open',
            'since'  => 'Q3 2026',
            'label'  => 'available for hire · q3 2026',
        ],
    ],
    'links' => [
        'email'    => 'danielsalipot@gmail.com',
        'phone'    => '+63 939 504 4799',
        'github'   => 'https://github.com/danielsalipot',
        'linkedin' => 'https://linkedin.com/in/daniel-andrei-salipot',
    ],
    'stats' => [
        ['n' => '10,000+', 'l' => 'cardholders live'],
        ['n' => '60,000',  'l' => 'students served'],
        ['n' => '12+',     'l' => 'production systems'],
    ],
    'now' => [
        ['label' => 'building',    'title' => 'Tapso',      'sub' => 'rfid attendance and cashless payments · sole developer · ~10 campuses live'],
        ['label' => 'maintaining', 'title' => 'Schoolaide', 'sub' => 'multi-tenant school SaaS · ~60 tenants · database-per-tenant'],
        ['label' => 'learning',    'title' => 'Go + Inertia.js', 'sub' => 'exploring a laravel-to-go migration for fun'],
    ],
    'projects' => [
        [
            'slug' => 'oasys', 'name' => 'OASYS', 'kicker' => 'Overall Administering System',
            'year' => '2023', 'featured' => true, 'tag' => 'Capstone · Best of department',
            'blurb' => "End-to-end Human Resource Information System with integrated Philippine-compliant payroll engine. Five user roles, twenty-plus modules, automated SSS / PhilHealth / Pag-IBIG / Withholding computation, and signed PDF payroll generation - built solo as the lead software engineer.",
            'stack' => ['laravel', 'php', 'mysql', 'bootstrap'],
            'lang' => 'php', 'branch' => 'main', 'hash' => 'a4f9c1d',
            'screenshot' => ['title' => 'oasys.adamson.local', 'subtitle' => 'hris · payroll · dtr · roles', 'tone' => 'forest'],
            'metrics' => [['20+', 'modules'], ['5', 'user roles'], ['Best', 'capstone 2023']],
            'case_study' => [
                'problem' => "HR departments in Philippine institutions juggle a brutal stack of paperwork - DTR tracking, leave applications, deduction tables, government contribution schedules (SSS, PhilHealth, Pag-IBIG, Withholding Tax), 15-day payroll cutoffs, and onboarding/offboarding paperwork - usually across spreadsheets, paper, and disconnected systems. There was no single source of truth: a payroll cycle could take days, leave requests got lost between approvers, and recomputing a deduction meant manual maths every cutoff.",
                'role'    => "Solo developer and lead software engineer / designer. Owned the entire system end-to-end: requirements gathering, database schema, role-based access control for five user types, all twenty-plus modules, the payroll computation engine (with Philippine government contribution tables), PDF generation with e-signature support, and deployment. Team of four total - the other members handled documentation, presentation, and research; the codebase and architecture were mine.",
                'outcome' => "Awarded Best Capstone of the IT&IS Department, Adamson University, 2023. The system runs the full HR lifecycle: applicant intake → onboarding → daily DTR and attendance → leave / overtime / cash advance workflows with approval chains → automated 15-day payroll computation → signed payroll PDF generation → offboarding. Tested with realistic employee data covering multiple positions, departments, and pay rates.",
                'links'   => ['live' => null, 'repo' => 'https://github.com/danielsalipot/OASYS'],
                'modules' => [
                    ['name' => 'Payroll Engine',       'desc' => '15-day cutoff cycles with automated computation of Gross, SSS, PhilHealth, Pag-IBIG, Withholding Tax, and Net Pay'],
                    ['name' => 'Salary Management',    'desc' => 'Per-position averages, top-earner rankings, and rate-per-hour editing with audit trail'],
                    ['name' => 'Deductions',           'desc' => 'Multi-employee bulk deduction creation, period-split across days, with approval and removal flows'],
                    ['name' => 'Overtime',             'desc' => 'Auto-detected from DTR excess hours, with approval / denial workflow and paid-overtime tracking'],
                    ['name' => 'Cash Advance',         'desc' => 'Request, approval, and amortization across pay periods, with running balance per employee'],
                    ['name' => 'Contributions',        'desc' => 'Government-compliant SSS, PhilHealth, Pag-IBIG, and Withholding Tax with bracket lookups per pay period'],
                    ['name' => 'Bonus & Multi-Pay',    'desc' => 'Ad-hoc bonus disbursement and multi-period payroll consolidation'],
                    ['name' => 'Leave',                'desc' => 'Application, approval workflow with manager routing, and balance accrual per employee'],
                    ['name' => 'Attendance & DTR',     'desc' => 'Daily time record with schedule comparison, late-tracking, and excess-hour detection'],
                    ['name' => 'Onboarding / Offboarding', 'desc' => 'Applicant pipeline from interview through hire to exit checklist, with status tracking'],
                    ['name' => 'Performance Assessment','desc' => 'Periodic evaluations with module-based scoring and HR Admin review'],
                    ['name' => 'Audit Logs',           'desc' => 'Cross-module activity log capturing who changed what, when, and from where'],
                ],
                'screenshots' => [
                    [
                        'src'     => '/projects/oasys/01-salary-management.jpg',
                        'caption' => 'Salary Management - per-position salary averages with top-3 earners per role and inline rate editing',
                        'alt'     => 'OASYS Salary Management page showing average salary per position cards with top earners listed',
                    ],
                    [
                        'src'     => '/projects/oasys/02-payroll-details.jpg',
                        'caption' => 'Payroll Details Table - per-employee row with auto-computed Total Hours, Rate/hr, Bonus, Gross Pay, SSS, Pag-IBIG, PhilHealth, Deductions, Taxable Net, Withholding Tax, and Total Salary',
                        'alt'     => 'Payroll details table with employee rows and computed columns including government contributions',
                    ],
                    [
                        'src'     => '/projects/oasys/03-payroll-report.jpg',
                        'caption' => 'Payroll Report Generation - 15-day cutoff picker with Create Payroll (e-signature upload + PDF output) and View Payroll History',
                        'alt'     => 'Payroll report generation panel showing current cutoff dates and create payroll button',
                    ],
                    [
                        'src'     => '/projects/oasys/04-overtime-approval.jpg',
                        'caption' => 'Overtime Approval Dialog - auto-detected excess-hour record awaiting Payroll Manager approval, with employee, schedule, and computed hours',
                        'alt'     => 'Continue to Pay Overtime modal showing employee details and computed excess hours',
                    ],
                    [
                        'src'     => '/projects/oasys/05-bonus-dialog.jpg',
                        'caption' => 'Bonus Disbursement Dialog - ad-hoc bonus entry that flows directly into the next payroll cutoff',
                        'alt'     => 'Bonus Details modal with date and amount fields',
                    ],
                ],
            ],
        ],
        [
            'slug' => 'ralli', 'name' => 'Ralli', 'kicker' => 'Badminton queue and rating platform',
            'year' => '2026', 'featured' => false, 'tag' => 'In progress',
            'blurb' => 'Session queue management for badminton courts: longest-wait-first bench ordering, live matchup generation, and an ELO rating engine. Laravel API with WebSocket broadcasting, paired with a React Native client.',
            'stack' => ['laravel', 'php', 'react', 'mysql'],
            'lang' => 'php', 'branch' => 'main', 'hash' => '1b45c35',
            'screenshot' => ['title' => 'ralli/queue', 'subtitle' => 'bench · matchups · elo', 'tone' => 'ocean'],
            'metrics' => [['24', 'tables'], ['67', 'client screens'], ['ELO', 'rating engine']],
            'case_study' => [
                'problem' => 'Open-play badminton sessions run on paper lists and shouted names. Players lose track of queue position, hosts rebuild matchups by hand between every game, and there is no record of who played whom or how balanced the matches were.',
                'role' => 'Solo developer. API design, 24-table schema, queue ordering, matchup generation, ELO and co-play history tracking, real-time broadcasting, and the React Native client.',
                'outcome' => 'Active build. Schema is frozen at v1 and documented. Core loop runs end to end: RSVP, bench queue with longest-wait-first ordering, matchup generation, set scoring, and ELO updates with history. Not yet released.',
                'links' => ['live' => null, 'repo' => 'https://github.com/danielsalipot/ralli'],
                'screenshots' => [
                    [
                        'src' => '/projects/ralli/ralli-web-2.jpg',
                        'caption' => 'Live session floor. Courts show the teams currently playing with per-game timers; the panel suggests the next match by fairness or skill level, with match history beneath.',
                        'alt' => 'Ralli session screen with two live badminton courts, team names, elapsed timers, and a match history list',
                    ],
                    [
                        'src' => '/projects/ralli/ralli-web-3.jpg',
                        'caption' => 'Queue and session stats. Longest-wait-first ordering with each player\'s games played and wait time, skill tags, and a resting list.',
                        'alt' => 'Queue tab showing five waiting players ordered by wait time with skill level tags and session statistics',
                    ],
                    [
                        'src' => '/projects/ralli/ralli-web-1.jpg',
                        'caption' => 'Venue dashboard. The running session is surfaced first, with upcoming nights showing format, court count, and fee.',
                        'alt' => 'Ralli dashboard listing a live session and three upcoming badminton sessions',
                    ],
                    [
                        'src' => '/projects/ralli/ralli-mobile-2.jpg',
                        'caption' => 'Host home on mobile. The live session shows elapsed time, players waiting, and collection progress against expected fees.',
                        'alt' => 'Ralli mobile home screen with a live session card showing elapsed time and payment collection progress',
                    ],
                    [
                        'src' => '/projects/ralli/ralli-mobile-4.jpg',
                        'caption' => 'Player profile. Per-sport ELO with win, loss and streak record, match history, and a trust score aggregated from peer reviews.',
                        'alt' => 'Ralli player profile showing badminton ELO, win and loss counts, and a trust score of 4.15 from five reviews',
                    ],
                    [
                        'src' => '/projects/ralli/ralli-mobile-1.jpg',
                        'caption' => 'Sign in. Email and password with Google OAuth as an alternative.',
                        'alt' => 'Ralli mobile sign-in screen with email and password fields and a continue with Google button',
                    ],
                ],
                'modules' => [
                    ['name' => 'Bench Queue', 'desc' => 'Longest-wait-first ordering with indexed hot-path queries on session, status, and join time'],
                    ['name' => 'Matchup Engine', 'desc' => 'Generates balanced pairings from the active bench, tracks per-set scoring'],
                    ['name' => 'ELO Ratings', 'desc' => 'Per-sport rating with full history for sparkline rendering and co-play weighting'],
                    ['name' => 'Trust & Reviews', 'desc' => 'Polymorphic reviews across hosts and players, aggregated into trust scores'],
                    ['name' => 'Realtime', 'desc' => 'Laravel Reverb WebSocket broadcasting so queue changes land on every client instantly'],
                    ['name' => 'Auth & Identity', 'desc' => 'Sanctum tokens for the mobile client, Socialite OAuth, push token registry'],
                ],
            ],
        ],
        [
            'slug' => 'terra', 'name' => 'Terra', 'kicker' => 'Hiking trip booking platform',
            'year' => '2026', 'featured' => false, 'tag' => 'In progress',
            'blurb' => 'Marketplace connecting hike organisers with joiners: trip listings with departures and price tiers, reservations, QR-coded meetups, payment submission review, and waitlists.',
            'stack' => ['laravel', 'php', 'livewire', 'mysql'],
            'lang' => 'php', 'branch' => 'main', 'hash' => 'c4e2b19',
            'screenshot' => ['title' => 'terra/trips', 'subtitle' => 'trips · reservations · hosts', 'tone' => 'forest'],
            'metrics' => [['23', 'models'], ['QR', 'meetup check-in'], ['Livewire', 'volt']],
            'case_study' => [
                'problem' => 'Local hiking groups organise trips through group chats and spreadsheets. Slots get double-booked, payment proofs get buried in message threads, and there is no reliable headcount at the meetup point on departure day.',
                'role' => 'Solo developer. Domain modelling across 23 models, host and joiner flows, reservation and waitlist logic, payment submission review, and QR-based meetup check-in.',
                'outcome' => 'Active build. Host trip creation, departures with price tiers, joiner reservations, waitlists, and QR meetup check-in are working. Not yet released.',
                'links' => ['live' => null, 'repo' => 'https://github.com/danielsalipot/terra'],
                'screenshots' => [
                    [
                        'src' => '/projects/terra/terra-1.jpg',
                        'caption' => 'Explore landing. Destination and host search over a full-bleed summit photo, with open trip and host counts.',
                        'alt' => 'Terra landing page with a sunrise mountain photo, search bar, and counters reading 39 trips open and 12 hosts',
                    ],
                    [
                        'src' => '/projects/terra/terra-4.jpg',
                        'caption' => 'Trip page. Host profile and rating, a what-to-bring checklist, and a booking panel with per-departure spot counts and per-person pricing.',
                        'alt' => 'Terra trip detail page for an island escape showing host, packing list, departure options, and a join trip button',
                    ],
                    [
                        'src' => '/projects/terra/terra-2.jpg',
                        'caption' => 'Joiner calendar. A month of departures with per-day trip counts, plus recovery for bookings made without an account.',
                        'alt' => 'Terra booking calendar for August with trip thumbnails and trips-to-join labels on each day',
                    ],
                    [
                        'src' => '/projects/terra/terra-3.jpg',
                        'caption' => 'Day drill-down. Selecting a date lists that day\'s departures with progress through multi-day trips and peso pricing.',
                        'alt' => 'Modal listing two trips available on a chosen date with prices and day-of-trip progress',
                    ],
                    [
                        'src' => '/projects/terra/terra-5.jpg',
                        'caption' => 'Host dashboard. Confirmed guests, payments awaiting confirmation, and unpaid holds above a schedule calendar showing capacity per departure.',
                        'alt' => 'Terra host dashboard with counters for confirmed guests, payments to confirm, and holds awaiting payment',
                    ],
                    [
                        'src' => '/projects/terra/terra-6.jpg',
                        'caption' => 'Public host page. Trips led, guests hosted, followers and rating, with the host\'s published departures below.',
                        'alt' => 'Public profile for a host organisation showing statistics and a grid of trips they lead',
                    ],
                ],
                'modules' => [
                    ['name' => 'Trips & Departures', 'desc' => 'Trip drafts through published listings with destinations, inclusions, hike details, and tiered pricing'],
                    ['name' => 'Reservations', 'desc' => 'Slot booking with participant records and automatic waitlist promotion'],
                    ['name' => 'Meetups', 'desc' => 'QR-coded meetup points with host presets for repeat departure locations'],
                    ['name' => 'Payments', 'desc' => 'Payment submission with proof upload and host-side review queue'],
                    ['name' => 'Host Profiles', 'desc' => 'Public host pages with posts, photos, and review aggregation'],
                    ['name' => 'Auth', 'desc' => 'Socialite OAuth plus magic-link sign-in for low-friction joiner onboarding'],
                ],
            ],
        ],
        [
            'slug' => 'date-tracker', 'name' => 'Date Tracker', 'kicker' => 'Local-first couples date journal',
            'year' => '2026', 'featured' => false, 'tag' => 'In progress',
            'blurb' => 'Expo app that models each date as a timeline of stops rather than one event. Fully local-first on SQLite, with on-device receipt OCR to capture what each stop cost.',
            'stack' => ['react', 'typescript', 'sql'],
            'lang' => 'typescript', 'branch' => 'main', 'hash' => '2ad9579',
            'screenshot' => ['title' => 'date-tracker', 'subtitle' => 'stops · memories · spend', 'tone' => 'plum'],
            'metrics' => [['28', 'screens'], ['Local', 'first'], ['OCR', 'receipt capture']],
            'case_study' => [
                'problem' => 'Shared-expense apps treat a night out as a single line item, which loses the shape of the evening. A date is usually several stops, and the memory of it lives in the sequence, not the total.',
                'role' => 'Solo developer. Data model, local-first persistence with Drizzle over SQLite, OCR capture pipeline, and the full UI including Skia-rendered views.',
                'outcome' => 'Active build. Date composition with multiple stops, per-date ratings, favourites, and the memories timeline are working. Not yet released.',
                'links' => ['live' => null, 'repo' => 'https://github.com/danielsalipot/date-tracker'],
                'modules' => [
                    ['name' => 'Stop Timeline', 'desc' => 'A date is composed of ordered stops, each with its own place, spend, and notes'],
                    ['name' => 'Receipt OCR', 'desc' => 'On-device ML Kit text recognition pulls totals from photographed receipts'],
                    ['name' => 'Memories', 'desc' => 'Chronological view of past dates with ratings and favourites'],
                    ['name' => 'Local-first Storage', 'desc' => 'Drizzle ORM over on-device SQLite, no account and no network dependency'],
                ],
            ],
        ],
        [
            'slug' => 'dumagat-remontado', 'name' => 'Dumagat Remontado', 'kicker' => 'University outreach informational site',
            'year' => '2022', 'featured' => false, 'tag' => 'University outreach',
            'blurb' => 'Cultural informational site for the Dumagat Remontado tribe (Adamson outreach).',
            'stack' => ['laravel', 'bootstrap'],
            'lang' => 'php', 'branch' => 'archive', 'hash' => 'e3b7c44',
            'screenshot' => ['title' => 'dumagat-tribe.ph', 'subtitle' => null, 'tone' => 'forest'],
            'metrics' => [['Outreach', 'project'], ['Adamson', 'university'], ['2022', 'shipped']],
            'case_study' => [
                'problem' => 'The Dumagat Remontado tribe lacked digital presence and accessible information about their culture.',
                'role' => 'Team developer - Laravel + Bootstrap implementation.',
                'outcome' => 'Public informational site supporting visibility of the tribe and its traditions.',
                'links' => ['live' => null, 'repo' => null],
            ],
        ],
        [
            'slug' => 'akai-tsuki', 'name' => 'Akai Tsuki', 'kicker' => 'Jewelry shop POS · desktop',
            'year' => '2019', 'featured' => false, 'tag' => 'Coursework',
            'blurb' => 'Windows desktop point-of-sale for a jewelry shop. Role-based login, tabbed product catalog across five categories, cart with VAT computation and change calculation, receipt printing, and user account management.',
            'stack' => ['c#', 'sql'],
            'lang' => 'c#', 'branch' => 'archive', 'hash' => 'a4a1t5k',
            'screenshot' => ['title' => 'AkaiTsuki.exe', 'subtitle' => 'pos · accounts · receipts', 'tone' => 'ember'],
            'metrics' => [['5', 'catalog tabs'], ['3', 'user roles'], ['2019', 'coursework']],
            'case_study' => [
                'problem' => 'Coursework brief: build a desktop point-of-sale. A jewelry counter made the requirements concrete. Items are individually identified rather than barcoded in bulk, staff need to see the piece before selling it, and every sale has to produce a correct receipt with Philippine VAT and cash change.',
                'role' => 'Solo build in C# WinForms against SQL Server. Designed the schema, the MDI shell and form navigation, the transaction and computation logic, receipt output, and role-based access across clerk, supervisor, and customer accounts.',
                'outcome' => 'Delivered as coursework in 2019. My first database-backed application and the first time I owned a full CRUD and transaction flow end to end. Source is lost, only screenshots survive.',
                'links' => ['live' => null, 'repo' => null],
                'screenshots' => [
                    [
                        'src' => '/projects/akai-tsuki/akai-tsuki-3.jpg',
                        'caption' => 'Point of sale. Item lookup and quantity on the left, cart and totals below, with the catalog tabbed across rings, necklaces, earrings, bracelets and watches. Computes 12% VAT, net total, and change, and stamps each sale with a transaction ID and cashier.',
                        'alt' => 'Akai Tsuki point of sale form with item entry, cart, tax and total fields, and a tabbed jewelry catalog',
                    ],
                    [
                        'src' => '/projects/akai-tsuki/akai-tsuki-2.jpg',
                        'caption' => 'Shell and user accounts. Sidebar navigation across the modules, with the account form open over it and a status bar reporting the active form.',
                        'alt' => 'Akai Tsuki application shell with a sidebar menu and the user account form open, listing clerk, supervisor and customer records',
                    ],
                    [
                        'src' => '/projects/akai-tsuki/akai-tsuki-4.jpg',
                        'caption' => 'Account management. Full create, update and delete over staff and customer records, searchable by username and typed by role and position.',
                        'alt' => 'User account form with fields for user type, username, name and position beside a searchable records table',
                    ],
                    [
                        'src' => '/projects/akai-tsuki/akai-tsuki-1.jpg',
                        'caption' => 'Login. Password visibility toggle, routing each role to the forms it is permitted to open.',
                        'alt' => 'Akai Tsuki login window with username and password fields under a red moon logo',
                    ],
                ],
                'modules' => [
                    ['name' => 'Point of Sale', 'desc' => 'Item lookup by ID, quantity stepper, running cart, 12% VAT and net total, amount given with change computation'],
                    ['name' => 'Product Catalog', 'desc' => 'Tabbed browsing across rings, necklaces, earrings, bracelets, and watches with per-item photo, ID, and material description'],
                    ['name' => 'User Accounts', 'desc' => 'Full CRUD over staff and customer records with username search, typed roles, and assigned positions'],
                    ['name' => 'Authentication', 'desc' => 'Login gate with password visibility toggle, routing each role to its permitted forms'],
                    ['name' => 'Receipts', 'desc' => 'Transaction ID and date stamped per sale, cashier attribution, printed receipt output'],
                    ['name' => 'Shell', 'desc' => 'MDI parent with sidebar navigation and a status bar reporting the active form'],
                ],
            ],
        ],
        [
            'slug' => 'ceresys', 'name' => 'Ceresys', 'kicker' => 'Cemetery reservation system',
            'year' => '2021', 'featured' => false, 'tag' => 'Coursework',
            'blurb' => 'Web system for reserving and locating cemetery plots. An interactive coordinate-grid map renders 178 plots across seven blocks with live availability, backed by deceased records, membership approval, and an admin console. Plain PHP and MySQL, no framework.',
            'stack' => ['php', 'mysql', 'js', 'css'],
            'lang' => 'php', 'branch' => 'archive', 'hash' => 'ce2e5y5',
            'screenshot' => ['title' => 'ceresys/map', 'subtitle' => 'plots · records · reservations', 'tone' => 'forest'],
            'metrics' => [['178', 'mapped plots'], ['7', 'blocks'], ['5', 'tables']],
            'case_study' => [
                'problem' => 'Finding a specific grave means asking staff or walking rows with a paper map, and finding an available plot means a trip to the cemetery office. Written during the pandemic, when both of those meant avoidable in-person contact for families already dealing with a loss.',
                'role' => 'Solo build in PHP and MySQL. Designed the schema, the coordinate grid the map is drawn from, the reservation transaction flow, the membership approval queue, and the admin console.',
                'outcome' => 'Delivered as coursework in 2021. The map renders every plot from stored coordinates with zoom, pan, and click-through to plot details, and a reservation ties a deceased record to an account and a specific grave. Source is archived locally and not published.',
                'links' => ['live' => null, 'repo' => null],
                'screenshots' => [
                    [
                        'src' => '/projects/ceresys/ceresys-3.jpg',
                        'caption' => 'Reservation map. Every plot is drawn from stored coordinates and colour-coded available, occupied, or owned. Selecting one opens its photo, block code, and location description.',
                        'alt' => 'Cemetery map with colour-coded grave markers, church, office and fountain landmarks, and a detail panel for grave 00129',
                    ],
                    [
                        'src' => '/projects/ceresys/ceresys-2.jpg',
                        'caption' => 'Member home after sign-in, with profile photo upload and the system\'s four capability summaries.',
                        'alt' => 'Ceresys member home page with a profile picture upload control and four feature descriptions',
                    ],
                    [
                        'src' => '/projects/ceresys/ceresys-1.jpg',
                        'caption' => 'Entry screen. Login and signup over the cemetery photograph.',
                        'alt' => 'Ceresys welcome screen with login and sign up buttons over a darkened cemetery photograph',
                    ],
                    [
                        'src' => '/projects/ceresys/ceresys-4.jpg',
                        'caption' => 'About page setting out the problem the system was built for: locating a relative\'s plot, and finding which plots are still available.',
                        'alt' => 'Ceresys about page describing the objectives of the cemetery reservation system',
                    ],
                ],
                'modules' => [
                    ['name' => 'Interactive Map', 'desc' => 'Plots drawn from stored X/Y coordinates with zoom, pan, per-plot click, and colour-coded availability across available, occupied, and owned'],
                    ['name' => 'Plot Registry', 'desc' => '178 graves across blocks A through G, each with a photo, block description, and landmark context such as the church, office, and fountain'],
                    ['name' => 'Deceased Records', 'desc' => 'Full record per interment: names, parents, birth and death dates, occupation, address, and photo'],
                    ['name' => 'Reservations', 'desc' => 'Transaction linking an account to a deceased record and a specific grave, driving the map state'],
                    ['name' => 'Membership', 'desc' => 'Signup request queue with admin approval or denial and a notification back to the requester'],
                    ['name' => 'Admin Console', 'desc' => 'User CRUD, grave listing, batch record entry, and membership status management behind a session guard'],
                ],
            ],
        ],
        [
            'slug' => 'wonder', 'name' => 'Wonder', 'kicker' => 'Art marketplace · school project',
            'year' => '2021', 'featured' => false, 'tag' => 'Coursework',
            'blurb' => 'Storefront for art materials, paintings, and sculptures. Category browsing, cart, order placement, and per-artwork comments, built in plain PHP and MySQL with no framework.',
            'stack' => ['php', 'mysql', 'html', 'css'],
            'lang' => 'php', 'branch' => 'archive', 'hash' => 'w0nd3r1',
            'screenshot' => ['title' => 'wonder/home', 'subtitle' => 'catalog · cart · comments', 'tone' => 'paper'],
            'metrics' => [['6', 'categories'], ['2021', 'coursework'], ['No', 'framework']],
            'case_study' => [
                'problem' => 'Coursework brief: build a working ecommerce site end to end. I picked an art marketplace so the catalog had to hold two different product shapes at once, consumable art materials with stock and price, and one-off artworks that also needed provenance text and a discussion thread.',
                'role' => 'Solo build. Schema, catalog and category routing, cart and order flow, comment threads, and the front-end. No framework, so sessions, queries, and templating were all hand-rolled.',
                'outcome' => 'Delivered as coursework in 2021. Source is lost, only screenshots survive. Kept here as an honest marker of where I started: the same catalog, cart, and moderation concerns I now solve with Laravel, written by hand at the time.',
                'links' => ['live' => null, 'repo' => null],
                'screenshots' => [
                    [
                        'src' => '/projects/wonder/01-landing.jpg',
                        'caption' => 'Landing page. Dictionary-entry hero setting the brand, with category nav across paintings, sculptures, and art materials.',
                        'alt' => 'Wonder landing page with a dictionary-style definition of the word wonder and a top navigation bar',
                    ],
                    [
                        'src' => '/projects/wonder/02-catalog.jpg',
                        'caption' => 'Art materials catalog. Sidebar category filter across six product groups, product grid with peso pricing and add-to-cart.',
                        'alt' => 'Colored pencils category page showing a sidebar of categories and a grid of product cards with prices',
                    ],
                    [
                        'src' => '/projects/wonder/03-artwork-detail.jpg',
                        'caption' => 'Artwork listing. Provenance copy alongside order placement and a per-artwork comment thread.',
                        'alt' => 'Artwork listing for the Venus of Willendorf with description, place order button, and a comment form',
                    ],
                ],
            ],
        ],
        [
            'slug' => 'skills-olympics', 'name' => 'Skills Olympics', 'kicker' => '1st runner-up · web design',
            'year' => '2022', 'featured' => false, 'tag' => '1st runner-up',
            'blurb' => 'Competition entry - represented Adamson at the I.T. Skills Olympics 2022, U-Makati.',
            'stack' => ['html', 'css', 'figma'],
            'lang' => 'html', 'branch' => 'competition', 'hash' => 'f48d910',
            'screenshot' => ['title' => 'olympics.entry', 'subtitle' => null, 'tone' => 'slate'],
            'metrics' => [['1st', 'runner-up'], ['~30', 'schools'], ['U-Makati', 'venue']],
            'case_study' => [
                'problem' => 'Competition brief: design a web page in a fixed time window evaluated by a panel.',
                'role' => 'Sole designer + developer - represented Adamson University.',
                'outcome' => '1st runner-up against ~30 schools.',
                'links' => ['live' => null, 'repo' => null],
            ],
        ],
    ],
    'stack' => [
        'backend'        => [['Laravel', 'primary'], ['PHP', 'primary'], ['Livewire', 'daily'], ['Filament', 'daily'], ['REST APIs', 'design + build']],
        'data'           => [['MySQL', 'primary'], ['Schema design', 'normalization'], ['Indexing', 'composite'], ['Query optimization', 'N+1 resolution'], ['Multi-tenant', 'db-per-tenant']],
        'integrations'   => [['PayMongo', 'payments'], ['GCash', 'reconciliation'], ['OpenAI API', 'summarization'], ['Webhooks', 'sync'], ['n8n · Zapier', 'automation']],
        'infrastructure' => [['Linux', 'server admin'], ['Azure · Cloudways', 'deployment'], ['SSL/TLS · SSH', 'ops'], ['Laravel Dusk', 'browser tests'], ['Git', 'daily']],
    ],
    'experience' => [
        [
            'from' => '07.2025', 'to' => 'current',
            'role' => 'Product Engineer I', 'org' => 'Rakso CT', 'loc' => 'Philippines',
            'note' => 'Own end-to-end backend delivery of Tapso, an RFID attendance and cashless payment platform running across roughly 10 school campuses, 80 field devices, and 10,000+ enrolled cardholders. Sole developer from data modelling and API design through deployment and production support.',
            'stack' => ['laravel', 'php', 'mysql', 'rfid', 'openai'],
            'projects' => [
                [
                    'tech' => ['Idempotency', 'Race conditions', 'Payments'],
                    'context' => 'Transaction handling for 500+ daily cashless payments, over PHP 2M in monthly volume. Duplicate detection and a 3-second tap cooldown removed double-charge and duplicate-attendance defects.',
                ],
                [
                    'tech' => ['Composite indexes', 'N+1 resolution'],
                    'context' => 'Recovered an attendance table of several hundred thousand rows from total timeout failure, restoring endpoints and report generation.',
                ],
                [
                    'tech' => ['Constraint satisfaction', 'Greedy optimization'],
                    'context' => 'Scheduling engine built from scratch enforcing teacher availability, subject hour quotas, double periods, and zero-gap timetables. School-wide schedules in about 30 minutes against a manual multi-day process.',
                ],
                [
                    'tech' => ['OpenAI API', 'Sentiment scoring'],
                    'context' => 'Summarizes and scores 500+ free-text evaluation records per teacher, replacing manual review with an automated reporting pipeline.',
                ],
            ],
        ],
        [
            'from' => '01.2023', 'to' => '07.2025',
            'role' => 'Web Application Developer', 'org' => 'Rakso CT', 'loc' => 'Philippines',
            'note' => 'Maintained and extended core modules of Schoolaide, a multi-tenant school management SaaS serving roughly 60 tenants and 60,000 students on a database-per-tenant architecture, sustaining peak write concurrency through enrollment, grade encoding, and ID release periods. One promotion and three merit increases across three years.',
            'stack' => ['laravel', 'livewire', 'filament', 'mysql', 'n8n'],
            'projects' => [
                [
                    'tech' => ['Incident recovery', 'Data migration'],
                    'context' => 'Restored a live production failure affecting an entire student cohort mid-examination. With no server access, replicated the database, validated a data-generation command against the replica, then applied corrected records to production inside the exam window.',
                ],
                [
                    'tech' => ['GCash', 'Reconciliation', 'Multi-tenant'],
                    'context' => 'Automated pipeline parsing consolidated daily transaction emails and dispatching balances to individual student wallets across tenant databases.',
                ],
                [
                    'tech' => ['Webhooks', 'System integration'],
                    'context' => 'Synchronization between the Schoolaide enrollment module and the Tapso RFID platform, provisioning newly enrolled students across system boundaries.',
                ],
                [
                    'tech' => ['QR codes', 'PayMongo', 'Event platforms'],
                    'context' => 'Backend for 8+ event registration systems covering payment tagging, QR-coded ID generation, and attendance capture. National events up to 6,000 attendees including PCNE and the CEAP General Assembly.',
                ],
                [
                    'tech' => ['Concurrency', 'Double-booking prevention'],
                    'context' => 'Wedding reservation SaaS for the Manila Cathedral covering the full booking lifecycle, roughly 100 bookings annually.',
                ],
            ],
        ],
        [
            'from' => '01.2022', 'to' => '12.2022',
            'role' => 'Web Developer (Project-Based)', 'org' => 'Adamson University', 'loc' => 'Manila, PH',
            'note' => 'Built an informational web platform for the Dumagat-Remontado indigenous community as part of the university community outreach program, improving public access to cultural documentation.',
            'stack' => ['laravel', 'php', 'bootstrap'],
            'projects' => [],
        ],
    ],
    'education' => [
        [
            'yr' => '2019 - 07.2023', 'degree' => 'BS Information Technology', 'org' => 'Adamson University · Manila',
            'note' => 'Capstone: OASYS (HRIS + payroll). Best of Department.',
            'honor' => 'summa cum laude', 'gpa' => '1.182 / 1.000', 'active' => true,
        ],
        [
            'yr' => '2017 - 2019', 'degree' => 'Senior High · STEM, Technology Track', 'org' => 'Adamson University · Manila',
            'note' => 'Foundations in programming, math, electronics.',
            'honor' => 'with honors', 'gpa' => null, 'active' => false,
        ],
    ],
    'certifications' => [
        [
            'org' => 'Microsoft', 'org_mark' => 'MS', 'org_bg' => '#00A4EF',
            't' => 'Technology Associate', 'sub' => 'Database Management Fundamentals',
            'yr' => '2021', 'cred' => 'MTA-098-DM', 'status' => 'verified',
            'skills' => ['sql', 'mysql', 'schemas', 'normalization'],
        ],
        [
            'org' => 'PSITE', 'org_mark' => 'PS', 'org_bg' => '#7C3AED',
            't' => '3rd Philippine Skilling Summit', 'sub' => 'Agile Methodologies Track',
            'yr' => '2022', 'cred' => 'PSS-22-AGM-417', 'status' => 'verified',
            'skills' => ['scrum', 'kanban', 'sprint planning'],
        ],
        [
            'org' => 'Adamson Univ.', 'org_mark' => 'AU', 'org_bg' => '#1F4D8B',
            't' => 'IT Skills Olympics 2022', 'sub' => 'Web Design · 1st Runner-up',
            'yr' => '2022', 'cred' => 'ITSO-22-WD-002', 'status' => 'verified',
            'skills' => ['html', 'css', 'figma'],
        ],
    ],
    'achievements' => [
        ['yr' => '2025', 't' => '1st Place',       'where' => 'Rakso CT Hack4Impact',  'note' => 'Team tech lead. AI platform recording live lectures into interactive mobile quizzes and downloadable flashcards, built end to end in about 20 hours.'],
        ['yr' => '2023', 't' => 'Best Capstone',   'where' => 'AdU IT&IS Department',  'note' => 'OASYS, an HRIS with payroll covering the full employee lifecycle.'],
        ['yr' => '2023', 't' => 'Summa Cum Laude', 'where' => 'Adamson University',    'note' => 'BS Information Technology, graduated July 2023.'],
        ['yr' => '2022', 't' => '1st Runner-Up',   'where' => 'I.T. Skills Olympics',  'note' => 'Web Design, representing Adamson against ~30 schools at the University of Makati.'],
        ['yr' => '2021', 't' => 'Microsoft MTA',   'where' => 'Database Fundamentals', 'note' => 'Technology Associate certification in database management.'],
    ],
];
